apiVersion: 1
contactPoints:
  - orgId: 1
    name: test
    receivers:
      - uid: eeaog6qghdou8e
        type: email
        settings:
          addresses: monitoring@digitalseeder.com
        disableResolveMessage: false
