FROM ubuntu:24.04
# Installer Apache et PHP et Mysql
RUN apt-get install -y apache2 libapache2-mod-php8.3 mysqli docker-php-ext-install pdo_mysql

# Copier la config Apache et le site web
COPY apache2/ /etc/apache2/
COPY www/ /var/www/
RUN a2dissite 000-default.conf \
 && a2ensite greenshop.conf \
 && a2enmod rewrite

RUN chown -R www-data:www-data /var/www/greenshop

# Exposer le port HTTP
EXPOSE 80